### ISSUE TITLE
Improperly looping through arrays

### ISSUE THREAD

**Issue by nicholashead** [MindscapeHQ/raygun4js#107]
The `_excludedHostnames` and `_excludedUserAgents` arrays are being looped through improperly. If there are any prototype functions attached to your Array object, they will be looped through (and cause an exception in Raygun4JS).

Proper way to handle this is to call `hasOwnProperty` on the array. I've fixed the issue, see below. Can someone please double-check/merge?

**Comment by fundead** [comment]
Thanks for spotting this one, just giving it a QA but it's looking good and will aim to get it out in a release this week.

Regards,

Callum Gavin
Mindscape Limited

**Comment by fundead** [comment]
This has been released as v1.18.2 and is now available from the package managers and the CDN (in the versioned folder). Once again thanks for your contribution here.
