### ISSUE TITLE
Stacktrace property is null on js windows store app causing further exception

### ISSUE THREAD

**Issue by paultuckey** [MindscapeHQ/raygun4js#113]
When throwing an exception in a JavaScript based windows store app (eg, `throw new Error('test')`) the stacktrace property of the exception is null.  This causes a problem in `computeStackTraceFromStacktraceProp` as it is not coded to cope with an empty stacktrace.

Specifically line 715 of dist/raygun.js v 1.18.3.

**Comment by fundead** [comment]
Thanks for reporting this one - we'll be looking at it shortly and will aim to get a fix out for it in the next release.

Regards,

Callum Gavin
Mindscape Limited

**Comment by Mabusto** [comment]
This is still breaking. More details in the comment on this commit : https://github.com/MindscapeHQ/raygun4js/commit/186ae91a5a5e387ca201c81445f38eecefb06f71

**Comment by fundead** [comment]
Thanks for raising this discovery - if you could open a new ticket for this one that would help us track it as it would be a separate bug to this old one which was WinJS specific.

Regarding the apparent undefined `stacktrace` seen in the latest Chrome, if you could also provide more details about where you saw that field be undefined (e.g how the original error was thrown that caused the error in Tracekit) that would be helpful as technically this should be idempotent across versions. I also assume this was seen in the mainline Chrome release and not Canary - could you also please provide your precise Chrome version number.

I do agree that the guard should check for undefined also, and will check with the latest implementation of the Tracekit dependency which the code concerned is from.
