### ISSUE TITLE
Update raygun to use the latest TraceKit release on bower/npm.

### ISSUE THREAD

**Issue by niemyjski** [MindscapeHQ/raygun4js#114]
I've merged in your custom changes into https://github.com/csnover/TraceKit and will be doing a new release version soon. Please submit pull requests / issues as you find them. We'd love to get your help.. I'll also be looking at ravens custom changes and bringing some of those in as well..

**Comment by niemyjski** [comment]
@fundead please let me know when you get some time.

**Comment by fundead** [comment]
Thanks for your work on merging the changes to our vendored Tracekit back into a maintained repo. At this stage our plans are to stick with that vendored version.

Regards,

Callum Gavin
Mindscape Limited

**Comment by niemyjski** [comment]
@fundead I wanted to let you know that I'm pushing a release very soon and you guys should update to it. I've added over 20 unit tests for different browsers and found a bunch of bugs with opera, IE and chrome.

**Comment by fundead** [comment]
Cheers for your work on that and the heads up, we've got a release queued up in the near term so I'll be sure to merge in the fixes.
