### ISSUE TITLE
Error infinite loop?

### ISSUE THREAD

**Issue by lee-houghton** [MindscapeHQ/raygun4js#115]
Hi there,

We were puzzled at why our Raygun account's error processing limit was exceeded within the space of about an hour. It turns out we received over 16000 errors from a single user!

The error seems to come from this line of code:
https://github.com/MindscapeHQ/raygun4js/blob/c7d8880045214ab6d403d5cc613c207f696a3cdd/src/raygun.js#L394

I don't know how invalid JSON got into the localStorage key, but it doesn't handle the error raised by JSON.parse, so that error then gets stored and raised itself. Is it possible that Raygun4JS has got itself into an infinite loop here?

**Comment by CmdrKeen** [comment]
Thanks for reporting this Lee. We'll take a look into this and see if we can handle the error and drop the data if it's invalid for some reason. 

If, by chance, this occurred on a system where you could extract the raw value from localStorage, I'd love to see what it is (always seems best to try to ensure dodgy data doesn't get persisted as well as not have issues rematerializing it).

**Comment by lee-houghton** [comment]
We do have data on who the affected users are, but would prefer not to contact them out of the blue if possible. They're all IE11 users, though. Maybe there is something broken about IE11's localStorage implementation?

**Comment by CmdrKeen** [comment]
Hi Lee,

Thanks for the insight about IE11 :+1: Callum will hopefully take a look at this today.

**Comment by fundead** [comment]
Just to let you know Lee I'm looking into this one now.
