### ISSUE TITLE
Android throws "Cannot call method 'getUUID' of undefined" when not sending a user to Raygun

### ISSUE THREAD

**Issue by EmilScherdin** [MindscapeHQ/raygun4js#118]

**Comment by fundead** [comment]
Hi,

Can you provide more details about this error - specifically the browser or app runtime you're seeing the error in, along with the stacktrace from the unminified raygun.js, and the exact case of the message (we don't use a `getUUID` function with that exact upper casing, so just need to confirm it's coming from the provider).

**Comment by fundead** [comment]
Hi again,

Closing this one for the current release as we need a stacktrace and environment to debug this and have no other reports at this stage. Feel free to open a new issue if you get this information on hand.

Regards,

Callum Gavin
Mindscape Limited
