### ISSUE TITLE
Uncaught TypeError: Object #<Event> has no method 'substring'

### ISSUE THREAD

**Issue by irongomme** [MindscapeHQ/raygun4js#119]
This error massively coming up from my clients, why ?

```
at ? line 143, column undefined (http://*********/js/src/raygun.js:143)
```

**Comment by fundead** [comment]
Thanks for reporting this - we're investigating and are working on a fix.

**Comment by fundead** [comment]
We have been unable to locate the source of this error and at this stage have no other reports; in many circumstances issues like this can occur when incorrect types are passed into library functions. If you can retrieve a full unminified stack trace please reopen this issue and we'll look at it again in the next release.

Regards,

Callum Gavin
Mindscape Limited

**Comment by lucifertran** [comment]
I also face the same problem as Dennis.

Possibly this could be the cause that make the application auto exit on it own.
Hard to trace why since it may be random.
