### ISSUE TITLE
Passing function to withTags breaks sending additional tags in raygun.send

### ISSUE THREAD

**Issue by Pwntastic** [MindscapeHQ/raygun4js#123]
Passing a function to raygun.withTags causes an error if additional tags are passed in raygun.send.

mergeArray is called with the tag function and additional tag array in raygun.send. The tag function isn't evaluated yet, and so it attempts to call concat on a function, which bombs.

This is in raygun.vanilla.js 1.18.4

**Comment by fundead** [comment]
Right you are, good spotting. We've got this queued up to be fixed in the next release which will be in the near term.

Regards,

Callum Gavin
Raygun Limited

**Comment by martynsmith** [comment]
@fundead - any ideas when this will be released (it's been 3 months?)

**Comment by fundead** [comment]
Apologies for the delay on this one, I was away when you message was posted and my team missed this one. This has now been fixed in the latest v2.3.0 release which is now up on the package managers, and the root CDN version will be updated tomorrow with it also if no issues are seen.
