### ISSUE TITLE
Chrome App error with localStorage

### ISSUE THREAD

**Issue by paultuckey** [MindscapeHQ/raygun4js#124]
In Chrome Apps (https://developer.chrome.com/apps/about_apps) `localStorage` is unavailable, even referencing it causes the following error: `window.localStorage is not available in packaged apps. Use chrome.storage.local instead`.

Is it possible for `localStorage` to only be queried if `Raygun.saveIfOffline(true)` has been called?

Thanks!

![developer_tools_-_chrome-extension___lbdiollaocpnafjeejkbjefopchcnheg_default_html](https://cloud.githubusercontent.com/assets/1170968/9457710/501f7af4-4b3a-11e5-8841-95e08f4d1e5a.png)

**Comment by fundead** [comment]
The latest v2.5.0 has a rewritten localStorage implementation and I believe there should be additional guards for this case - if anyone notices this issue in future please let us know and we'll take another look.
