### ISSUE TITLE
Add a option to exclude ajax errors by HTTP Status Code

### ISSUE THREAD

**Issue by jamiepenney** [MindscapeHQ/raygun4js#127]
Similar to this in raygun4net https://github.com/MindscapeHQ/raygun4net#additional-aspnet-configuration-options

**Comment by xt0rted** [comment]
Just ran into this with [402](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#402) status codes. I'm using them to trigger a payment UI to show before allowing the user to continue, but raygun is logging these as errors. Would be nice to allow filtering these out.

**Comment by fundead** [comment]
Apologies for the delay in response to this ticket. The API is getting a bit baroque here so to avoid bloating it further this can be handled with onBeforeSend as at https://github.com/MindscapeHQ/raygun4js#onbeforesend, by using it to inspect the Request object for the desired status codes and returning false to cancel. If you need further assistance please let us know.
