### ISSUE TITLE
Raygun modifies objects passed as custom data

### ISSUE THREAD

**Issue by unkillbob** [MindscapeHQ/raygun4js#133]
We had a strange bug in production where we were losing data, certain objects were not getting saved to IndexedDB. We discovered this was because at some point we were passing that object as custom data to Raygun which resulted in it getting modified - all prototype methods got copied onto the object itself - rendering the object incapable of being written to IndexedDB.

Further debugging revealed that custom data is passed through the [`filterObject`](https://github.com/MindscapeHQ/raygun4js/blob/master/src/raygun.js#L445) method which seems to modify the object itself rather than creating a filtered copy.

**Comment by dwnz** [comment]
Will be looking at this today :)

**Comment by dwnz** [comment]
Hey @unkillbob, 

Have just updated Raygun4JS so that it creates a new filtered object, leaving the original one alone. Thanks for the feedback!

**Comment by unkillbob** [comment]
Thanks @dwnz, much appreciated!
