### ISSUE TITLE
Passing through rg4js calls after raygun has loaded

### ISSUE THREAD

**Issue by Neaox** [MindscapeHQ/raygun4js#144]
Hi,

We have written a react web app which loads the user profile asynchronously.

Currently we are loading raygun asynchronously using your snippet (https://github.com/MindscapeHQ/raygun4js/blob/master/src/snippet/minified.js).
Initial calls (setting options) and errors are queued into an array which is then processed when raygun loads.

As our user profile loads asynchronously (via fetch request) there is a race condition; the user profile could load before raygun does.

To get around this we need to use something like the following code:

```
if(Raygun)
  Raygun.setUser(1234, false, 'joe.bloggs@domain.com', 'Joe Bloggs', 'Joe);
else if(rg4js)
  rg4js('setUser', {
    identifier: 1234,
    isAnonymous: false,
    email: 'joe.bloggs@domain.com',
    firstName: 'Joe',
    fullName: 'Joe Bloggs'
  });
```

What would be helpful is to be able to use `rg4js` everywhere, and when raygun has loaded `rg4js` is remapped to pass the call through to the appropriate Raygun function. Would this be possible?

**Comment by fundead** [comment]
Hi,

This provider has just received a new release which contains improvements to rg4js() for config functions. This should now proxy through calls like rg4js('setUser', ...) calls through to the classic `Raygun` object, removing the need for your workaround as requested. Hope this helps!

Regards,

Callum Gavin
Raygun Limited
