### ISSUE TITLE
Add memory usage to crash reports

### ISSUE THREAD

**Issue by jamiepenney** [MindscapeHQ/raygun4js#155]
You can get this info from the Navigation Timing API
http://stackoverflow.com/questions/2530228/jquery-or-javascript-to-find-memory-usage-of-page

Probably should go under the `enviroment` section in the crash report.
https://raygun.io/docs/integrations/api

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
