### ISSUE TITLE
Exclude noisy AJAX false positives

### ISSUE THREAD

**Issue by jiaweihli** [MindscapeHQ/raygun4js#157]
We recently upgraded to the new version of Raygun, and we're seeing a lot of false positives.
`AJAX error: abort POST` errors seem to be racking up, either due to user redirection or intentional cancellation by us.  Can these be filtered out by default?  There doesn't seem to be anything we can do on our end.

http://stackoverflow.com/a/18170879/759714 might be useful.

**Comment by fundead** [comment]
Thanks for reporting this, I've managed to repro the case locally and am working on a fix. Will get that out in a point release once it's good to go.

**Comment by fundead** [comment]
An update: looks like the current release is handling this when configured with the following statement, containing or or all of these parameters depending on what you want to ignore:

```
  rg4js('options', {
    ignoreAjaxError: true,
    ignoreAjaxAbort: true,
    ignore3rdPartyErrors: true
  });
```

That should be added after your apiKey set statement. This will result in the appropriate Ajax errors being ignored on cancels or aborts. The third one may be optional if you have CORS configured on scripts loaded from non-origin domains.

Hope this helps!

**Comment by jiaweihli** [comment]
Right, I just discovered this too.  Sorry for the fanfare!
