### ISSUE TITLE
Setting filter scope to 'all' breaks api call

### ISSUE THREAD

**Issue by eeggen-rhinofly** [MindscapeHQ/raygun4js#158]
When I call `setFilterScope('all');` the code filters out the fields `occurredOn` and `Details.Client` in addition to the keys set in `filterSensitiveData()`. This breaks the api call to https://api.raygun.io/entries. Is this by design?

**Comment by fundead** [comment]
Thanks for reporting this one, indeed this was a regression in the filtering logic, and I have pushed a PR containing a fix for just now.

Are you bundling the script or referencing the CDN? If you wish to download one of the artifacts from the above branch or reference the CDN path `//cdn.raygun.io/raygun4js/2.1.1/raygun.min.js` you'd be able to confirm the fix which would be a help. This tests well for us though so I'll look at getting this merged into master soon.

**Comment by eeggen-rhinofly** [comment]
No worries! We are bundling the script. However, there is no inconvenience at this point, since I have decided to switch the filter scope to `customData`. I'll be sure to check it out if I ever need to switch back to `all`.

**Comment by fundead** [comment]
Good to hear, just a heads up that this has been now released as v2.1.1. Hope Raygun continues to prove useful for you and your team!
