### ISSUE TITLE
raygun 2.1.1 not available via npm

### ISSUE THREAD

**Issue by abloomston** [MindscapeHQ/raygun4js#162]
https://www.npmjs.com/package/raygun4js says "2.1.0 is the latest of 5 releases"

If I include `"raygun4js": "^2.1.1"` under `dependencies` in `package.json` I get the following error when running `npm install`:

<pre>
npm ERR! notarget No compatible version found: raygun4js@'>=2.1.1 <3.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.18.3","1.18.5","1.18.6","1.18.7","2.1.0"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'project-web-app-client'
npm ERR! notarget 
</pre>

**Comment by fundead** [comment]
Sorry about that! v2.1.1 is now up and available on NPM now.
