### ISSUE TITLE
CustomData keys with null being filtered

### ISSUE THREAD

**Issue by abloomston** [MindscapeHQ/raygun4js#163]
Fields in CustomData whose value is null are being filtered out before sending the error to the Raygun backend.

Using v2.1.0 (not v2.1.1, due to https://github.com/MindscapeHQ/raygun4js/issues/162) if I use the following method for custom data (`.withCustomData(customData)`):

<pre>
function customData() {
	return {
		foo: null,
		bar: {
			foobar: null
		}
	};
}
</pre>

and manually send an error via calling `Raygun.send` then the keys `foo` and `bar.foobar` are filtered out of the custom data.

I see the following with `debugMode: true` for the error in the javascript console:

<pre>
UserCustomData: Object
bar: Object
__proto__: Object
__proto__: Object
</pre>

I see the following under the "Raw data" in the Raygun frontend:

<pre>
"UserCustomData": {
          "bar": {}
     },
</pre>

**Comment by fundead** [comment]
Thanks for this ticket, you're correct in that we shouldn't be stripping out the null values. I'll attempt to get a release up containing a fix for this soon as practicable.
