### ISSUE TITLE
Provide a way to initialize TraceKit's jquery support when using async script

### ISSUE THREAD

**Issue by aaronjensen** [MindscapeHQ/raygun4js#165]
Currently, if I use the async snippet, raygun.js may load before jquery does. If it does, then TraceKit's jquery support won't be enabled. Furthermore, if I don't put jquery on window because I use webkit, it won't matter when raygun.js loads because it won't ever see window.jQuery. Ideally there'd be a function we could call and pass it jQuery to do the initialization at that time.

Example:

``` js
rg4js('initJquery', $)
```

**Comment by fundead** [comment]
Good catch - this function should indeed be available. I've got this queued up for the next release which will be in the near term.

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
