### ISSUE TITLE
Response to preflight request doesn't pass access control check

### ISSUE THREAD

**Issue by jgentes** [MindscapeHQ/raygun4js#168]
Hey guys, I'm seeing this with the JS agent when an exception is thrown locally:

`XMLHttpRequest cannot load http://cdn.raygun.io/raygun4js/raygun.min.js. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access. The response had HTTP status code 403.`

Seems like this is a CORS issue on your server, no?

**Comment by fundead** [comment]
Hi,

I'm seeing the CORS headers correctly transmitted, as with:

```
curl -I -s -X GET -H "Origin: www.example.com" http://cdn.raygun.io/raygun4js/raygun.js
```

and when the `crossOrigin` attribute is placed on the script tag in the browser. Are you using the V2 API with the snippet?

**Comment by jgentes** [comment]
Ah, I was loading the script twice. First with the v2 snippit then again with bower. Removed the first and it cleared up - thanks!
