### ISSUE TITLE
Raygun 2.2.1 breaks in IE8 

### ISSUE THREAD

**Issue by onelifenyc** [MindscapeHQ/raygun4js#171]
delete window.__instantiatedRaygun;
Object doesn't support this action

![image](https://cloud.githubusercontent.com/assets/4038782/12464925/94bc9e0c-bf99-11e5-8246-e8f3c0cd34e3.png)

**Comment by fundead** [comment]
Thanks for reporting that - getting a fix up for it now.

**Comment by onelifenyc** [comment]
Thanks!

Saw this fix for it 

http://stackoverflow.com/questions/1073414/deleting-a-window-property-in-ie

We have a number of pages running in IE8 mode so raygun reports are blowing up with "Script error" which luckily are silent to the users.

**Comment by fundead** [comment]
Bingo, that's the one. I shouldn't be surprised that IE8 doesn't have `delete` but..

We're just invalidating the edge caches with the fix on the CDN now, should be ready worldwide in about 10 minutes. Fortunate that it's silent but apologies for the disruption anyway!

**Comment by onelifenyc** [comment]
Sorry for not responding earlier. Like expected, fix works - thanks for getting it done quickly.

**Comment by onelifenyc** [comment]
Hi,

We are still seeing Raygun report issues with Script error and we can see the users are with Client as follows : 

     "Client": {
          "Name": "raygun-js",
          "Version": "2.2.1"
     },

we even have a log of someone with 

     "Client": {
          "Name": "raygun-js",
          "Version": "2.1.0"
     },

Is it possible the CDN didn't refresh properly worldwide? Can you refresh it or should we use our version string at the end of the raygun.min.js - but that doesn't make sense because we can't keep track of your releases or hotfixes.

I see everything ok in Fiddler (see below) and makes sense of the times that you were releasing at 5:50PM ET - when you published at 7:20PM - but how do we explain and fix it for other users who are not getting the 2.2.2 version? 

Request Header:  
* If-Modified-Since: Wed, 20 Jan 2016 22:48:21 GMT

Response Header 
* Age: 61374
* Date: Thu, 21 Jan 2016 15:57:20 GMT
* X-Cache: Hit from cloudfront
* X-Amz-Cf-Id: _3_QBwj_u1sNDjOfhITTsPUvjsTJJ4gg0C6R3HggJT7NrVX-xxbjYA==


Thanks in advance.

**Comment by fundead** [comment]
The CDN has been invalidated correctly and the latest v2.2.2 version is available from all edge nodes, however you'll see some clients who haven't invalidated their local caches. This is due to client's varying implementations of Cache-Control. For the next update I will lower the timeout to reduce the impact of this, so the clients refresh quicker. You could avoid this by specifically referencing the latest version of the script in the snippet:

```
"//cdn.raygun.io/raygun4js/2.2.2/raygun.min.js"
```
