### ISSUE TITLE
raygun4js v2.2.2, Safari 7.1: TypeError: undefined is not an object (evaluating 'e.performance.now')

### ISSUE THREAD

**Issue by m-o-e** [MindscapeHQ/raygun4js#173]
We frequently see the following error in Safari 7.1:

```
TypeError: undefined is not an object (evaluating 'e.performance.now')
  at performance(~/raygun4js/dist/raygun.js:2273:0)
```

**Comment by fundead** [comment]
Thanks for reporting this, we're looking at getting a fix out for this today.

**Comment by fundead** [comment]
Just an update on this, there is now a fix in master for this with more precise guards, if you're using the CDN it's now available at `http://cdn.raygun.io/raygun4js/2.2.3/raygun.min.js`. We're just running QA on our own sites and if this performs well it'll be available on the CDN as the root and released to the package managers tomorrow.

**Comment by m-o-e** [comment]
Thanks!
