### ISSUE TITLE
Misleading text in README.md

### ISSUE THREAD

**Issue by bluesmoon** [MindscapeHQ/raygun4js#175]
The `README.md` file contains the following text after the loader snippet:

> This will fetch the raygun4js script from our CDN asynchronously, so it doesn't block the page load.

However this is misleading as the method used for loading the script will in fact block page load.  The script will download asynchronously and will not block other assets from downloading, but the page's `onload` event will still block until the script has completed loading.

In the event of a network or CDN failure where the script is unable to load or times out, this will block the host page from completing its load for a long period of time.

The issue is explained in detail on the Performance Calendar from 2012:
http://calendar.perfplanet.com/2012/the-non-blocking-script-loader-pattern/
and here: http://www.lognormal.com/blog/2012/12/12/the-script-loader-pattern/

My recommendation would be to update the loader snippet to be truly non-blocking.  If that is not possible, then it is better to update the readme stating that this will block onload and cause a 3PoF.

Let me know if you need any help implementing the loader.

**Comment by fundead** [comment]
Hi,

Thanks for bringing this one up - we'll be clarifying the docs to state that it doesn't block additional script tags loading/parsing/executing which was the intended sense (any implication that it doesn't prevent onLoad was not intended).

Interesting approach using an iframe with content added at a later time. We adopted the async=1 attribute on the inject script tag as this was semantic and specifically supported by browser APIs, and was/is the approached used in Google Analytic's analytics.js, which has been proven and battle-tested. Naturally we desire to get as close to truly asynchronous as possible and not block where possible, however the aim is a consistent and safe implementation across as many browsers as possible, both evergreen and legacy. As such we continue to work on a testing regime to confirm the wildly varying behaviours we've seen for the apparently simple use case of loading a script. These tests will need to be finished and verified before we make any additional changes to the snippet, but we intend to look at this again down the track.

A key point would be to only introduce the complexity of the unintended iframe behaviour if this proves to be a major pain point, and both old and new browsers are confirmed to support it both now and in the future. As you're no doubt aware the page load processing model is rather intricate and full of edge cases, and where possible we aim to remain both backward and forward compatible.

Once again thanks for raising this one, we'll be revisiting this in the future.

Regards,

Callum Gavin
Raygun Limited
