### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by toddca** [MindscapeHQ/raygun4js#179]
Using the new api such as 
`rg4js("apiKey", "mykey")`

How do you manually send a error?

I have tried the following and it does not work:
`rg4js("send",new Error("This is a manual error"))`

The example in this repo uses a Raygun object that is never defined.

**Comment by toddca** [comment]
Disregard - the window.Raygun object does not populate right away and we needed to wait a bit.

**Comment by fundead** [comment]
You're correct in your discovery there - currently `rg4js` only performs initial configuration. We're planning to add functionality to proxy through calls to the Raygun object regardless of when it is loaded, this requires us to enhance our test infrastructure to confirm no breaking changes and will be completed in the near term, removing the need for you to wrap `Raygun` calls e.g in a `ready` handler.
