### ISSUE TITLE
Track custom HTTP Header from ajax error response

### ISSUE THREAD

**Issue by nicotaing** [MindscapeHQ/raygun4js#183]
I was wondering if we could add http header response from an a failing ajax request?

It would look like:

``` javascript
        Raygun.send(thrownError || event.type, {
            status: jqXHR.status,
            // other attributes
            responseHeaders:  responseHeaders
        });
```

If it's not something you guys are planning to add, I'll be happy to try to open a PR?

**Comment by fundead** [comment]
Thanks for this suggestion, it looks like a valuable one to have in the provider. We didn't have it on our list but if you were to send a PR I can look at getting it merged and included with the next release.

Regards,

Callum Gavin
Raygun Limited

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
