### ISSUE TITLE
VirtualPageLoad ignored in unloadHandler

### ISSUE THREAD

**Issue by frederikprijck** [MindscapeHQ/raygun4js#186]
Dear,

I'm having difficulties in using the trackEvent method to track custom pageviews.

I've created two JSFiddle's to help demonstrate the issue, all you have to do is fill in your API Key in order to sent the events to your Raygun Pulse account.

When I use this fiddle: https://jsfiddle.net/frederikprijck/p3s3u2tv/ 
I do not see the custom Page View in Pulse: http://prntscr.com/bbbdx3, not even when triggering the unloadHandler.

However, when I use this fiddle: https://jsfiddle.net/frederikprijck/zbbmvwzm/
I see the custom Page View in Pulse: http://prntscr.com/bbbe6q, however I think this is not how your api is supposed to be used ...

After debugging the source code, I came to the conclusion that virtualPageLoads are not sent inmediatly, but instead are tracked in memory and only sent when a new pageview is sent.

This sounds perfectly normal in a real Single Page Application, however I wonder what happens with the last pageView ... 
After looking into the sourcecode I found the 'unloadHandler', but this does not persist the pendingVirtualPage at all. So if I am correct, the last virtual page load is lost when navigating away from the application.

Basicly what we would like to achieve is the following:

- Track a single custom pageView
- Ensure it's being persisted when the user leaves the page or include in the heartbeat to keep track of the total time spent on the custome pageVIew. Both solutions could be valid, aslong as the data gets persisted without calling a second trackEvent.

BTW: I'm not sure this is a bug, or I am simply misunderstanding raygunjs ...

**Comment by fundead** [comment]
Hi,

You're understanding the current behaviour of Pulse's virtual page logic in Raygun4JS quite well - the library stores a pageView in-memory but does not immediately send it; only upon the next pageView is the previous one sent. The reason for this is the lack of a true application view lifecycle concept in the browser - we're working around an environment that was designed for static documents and as such the semantics around lifecycle hooks such as 'onClose' aren't first-class citizens.

The reason for delaying the previous pageView until the next one is to get the viewing time, from one pageView to another, which naturally is defined as the time when the next pageView is tracked. This then leaves the case open for the final pageView which doesn't have a subsequent one.

Your second jsfiddle does correctly send the first pageView but does so with a duration of ~0ms (or however long the runtime marks the hires timestamp as).

Despite that I can think of changes that can be made to the unloadHandler that can persist this final pageView correctly, recording the available data and make it available for sending upon the next time the page is visited. This would thus only be available in the case the unloadHandler is called and the page is loaded again - for instance, a device power-off or similar state would not register a pageview.

However, the above changes are certainly possible and we will look at implementing them for you so the majority of final pageViews are sent with their duration when possible. It will require a bit of experimentation and QA to get this working reliably cross-browser though. This work will be conducted in an upcoming sprint, and we'll get back to you on this soon.

Regards,

Callum Gavin
Raygun Limited

**Comment by frederikprijck** [comment]
Well I guess one can never prevent oneanother to turn of his PC (or it could have crashed).
I guess in such cases it is acceptable to ignore the last pageView ...

So I agree that adding it to the unloadHandler isn't realy a bulletproof fix. But I think we can see it's that 1% better if handled in the unloadHandler.

Thanks for the reply, looking forward to the fix in the future!

**Comment by frederikprijck** [comment]
Any timeframe on this ?

**Comment by fundead** [comment]
Apologies for the delay, I'm bumping this to the top of the queue for you and will tackle it shortly.

**Comment by fundead** [comment]
This is now up on the CDN as a prerelease version at http://cdn.raygun.io/raygun4js/2.3.4/raygun.js, the fix appears to be working well and solving the use case for me and we're integrating it for our sites to confirm the change. If you wanted to reference the CDN version or install it off the branch that would help the QA, but if it looks good for us we'll cut a release for the package managers in the next day or so.

**Comment by frederikprijck** [comment]
Any idea when 2.3.4 will be released ? I'll use the prerelease version in the meanwhile and verify if it works. I'll keep you posted !

**Comment by fundead** [comment]
This branch has been working well for us and has been QA'd so I will perform the release now. Hope this improves Raygun for you and your team.

**Comment by frederikprijck** [comment]
I was wondering ... Currently it's not correctly displaying the time spent on the page:
E.g. when opening a specific page I invoked the trackEvent method and I wait for +/- 60 seconds, next I leave the page in order to send the data to pulse.

However pulse shows the following: http://prntscr.com/bspmxj

Both the index.php and the custom path come from the same page view: The index.php is the default pulse page view, the other one is for the custom tracked pageView event. I expect the timings to be +/- the same, but they are not.

I didn't debug ur code yet. I will do so but I prefered to notify you on this.

**Comment by frederikprijck** [comment]
One other remark I have: Isn't it odd that the custom tracked events are published (or atleast displayed) to raygun before the default page tracking ?

On my screenshot above, you can see 2 entries: index.php and a custom tracked one.
In my case index.php is the first page and inside that page the custom events are happening and tracked. However, index.php (which happens before the custom event) is shown in raygun after the custom tracked events.

**Comment by fundead** [comment]
Ah, thanks for reporting that, you've come across an edge case in the backend behaviour. There is somewhat subtle behaviour here as technically virtual events could be performed before the static pageload event, as the latter is only fired after the DOM and all scripts are loaded, parsed and ready to go. With the async nature of the browser it's possible and in some cases desirable to have a loading view displaying while the rest of the app is bootstrapping, and such a view could have hooks to send virtual pageView events during its lifecycle.

However as you've noted this is pretty unintuitive in your case. We'll have a think about how to best handle this, it may result in the pageView events having their min timestamp set to the static page load time, ensuring the latter is always first in the UI. We perform a bunch of sanitization on the backend for the timing data as a whole so it's no trouble to add this in. That approach would leave other events open to not being 'snapped' to the static load time, if that behaviour is wanted instead.

We'll get back to you on this - thanks for raising the issue.

**Comment by frederikprijck** [comment]
Hi, Any timeframe on this ? 

Can we reopen this issue or do I need to make a new one ?
