### ISSUE TITLE
Should be able to send manual errors with rg4js

### ISSUE THREAD

**Issue by jbedard** [MindscapeHQ/raygun4js#191]
Otherwise you have to use the v1 `Raygun.send` API. This also assumes that `Raygun` has actually loaded already.

**Comment by fundead** [comment]
Hi,

We have a candidate v2.4.0 release containing an addition to the V2 API supporting this use case, this is currently in PR #190 and is up on the CDN at http://cdn.raygun.io/raygun4js/2.4.0/raygun.min.js. The addition is allowing calls of the form `rg4js('send', error)` to proxy through to Raygun.send at any time during the page lifecycle. As it currently stands it has a breaking change with regards to the position of the config statements (currently requires them in the HEAD as opposed to the end of the body). I'm planning on having another pass over this and attempting to remove the breaking change, and I'll ensure some time is assigned to work on this in the near future for you.

In the meantime, if you did want to point your raygun4js at the above artifact and move your apiKey and `enable` statements into the head, below the loader snippet, this should get it working for you. Let us know how it goes.

**Comment by jbedard** [comment]
I think #190 will solve it.  For now I can't upgrade to v2 due to this issue and #192 though.

**Comment by fundead** [comment]
#190 has now been released and exposes `rg4js('send', error)` for manual error sending with the V2 API. We're still working on your other ticket and I will get back to you shortly for the best architecture for your use case.
