### ISSUE TITLE
Where is the last version?

### ISSUE THREAD

**Issue by linuxonrails** [MindscapeHQ/raygun4js#196]
CDN: /*! Raygun4js - v2.4.1 - 2016-09-07

MindscapeHQ/raygun4js: /*! Raygun4js - v2.4.0 - 2016-09-06

**Comment by fundead** [comment]
Apologies for the delay in response to this ticket. We received spurious reports from users that the tagged v2.4.0 release failed to send under some circumstances, a fix was pushed in v2.4.1 to the CDN to confirm any erroneous behavior as this one was hard to repro and we aim to avoid regressions and further runtime bugs whereever possible. With regards to the tagged releases, these are used by the package managers to install the script so any potential bugs become more persistent so we're careful about creating new tagged releases until they are known good.

As we've received no further reports about any bugs in v2.4.1 I'm happy to create a release now and push them up to the package repositories. These will be available shortly.
