### ISSUE TITLE
[Question] Include arbitary information into setUser

### ISSUE THREAD

**Issue by dentuzhik** [MindscapeHQ/raygun4js#198]
Is there any way to include arbitrary information for the user? F.e., when using oauth for SPA, I want to send a scope of the token alongside all the other information, but as far as I can see in the api, it's not possible.

**Comment by fundead** [comment]
Currently this isn't possible but is something we'd be open to implementing for you. As this would require a bunch of end-to-end work surfacing this data in the UI the best action is to create a feature request at https://raygun.com/thinktank/forum/4 which we use when planning upcoming work. Our Product Manager can then put it on the roadmap and schedule it.

Regards,

Callum Gavin
Raygun Limited
