### ISSUE TITLE
Raygun reporting errors in Edge only when LastPass is installed

### ISSUE THREAD

**Issue by xt0rted** [MindscapeHQ/raygun4js#200]
I'm running the latest version of Edge and installed the LastPass plugin to try it out. When I load any of the forms on my site that LastPass adds its little icon to Raygun ends up reporting a SyntaxError.

If I turn off the plugin the error reports stop, turn it back on and they start again. There's no other information being reported with this. I'm not seeing any errors being reported in the console either.

I'm not familiar with how browser plugins work but is it possible for them to trigger the on-page error reporting and that's what I'm seeing?

This is the raw error report off the site.
```json
{
  "Error": {
    "ClassName": "Error",
    "Message": "SyntaxError",
    "StackTrace": [
      {
        "LineNumber": null,
        "ColumnNumber": null,
        "ClassName": "line null, column null",
        "FileName": null,
        "MethodName": "function ()"
      }
    ]
  },
  "Environment": {
    "UtcOffset": -4,
    "Browser-Width": 1280,
    "Browser-Height": 603,
    "Screen-Width": 1280,
    "Screen-Height": 720,
    "Color-Depth": 24,
    "Browser": "Mozilla",
    "Browser-Name": "Netscape",
    "Browser-Version": "5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.14955",
    "Platform": "Win32"
  },
  "Client": {
    "Name": "raygun-js",
    "Version": "2.4.1"
  },
  "UserCustomData": {
    "handler": "From Raygun4JS snippet global error handler"
  },
  "Tags": [
    "website",
    "portal"
  ],
  "Request": {
    "Url": "https://*****/account/register",
    "QueryString": {},
    "Headers": {
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.14955",
      "Referer": "https://*****/Account/Login?ReturnUrl=%2F",
      "Host": "*****"
    }
  },
  "Version": "0.2.0",
  "User": {
    "Identifier": "*****",
    "IsAnonymous": true,
    "UUID": "*****"
  },
  "OccurredOn": "2016-11-04T10:58:55.579Z"
}
```

**Comment by CmdrKeen** [comment]
Hi,

I don't know specifically about Edge, but I know in Chrome the extensions run in the JavaScript context of the page you're viewing. This can result in the error handler being triggered when extensions have issues. The best approach would be to filter them out using an inbound filter (probably on the message, since the user agent, IP, etc would all be the same for normal errors). You can see the inbound filters in the side bar of Raygun under Crash Reporting.

Perhaps @fundead has some ideas on how we could detect if an issue arises from an extension in Edge (and probably Chrome) so that we could add a tag or something similar automatically, making filtering easier.

**Comment by xt0rted** [comment]
We just had a similar error get logged from Chrome on iOS. This looks to be a known issue that hasn't been fixed yet https://bugs.chromium.org/p/chromium/issues/detail?id=590375

Here's the error details if it helps at all.

```json
{
     "Error": {
          "ClassName": "TypeError",
          "Message": "undefined is not an object (evaluating '__gCrWeb.autofill.extractForms')",
          "StackTrace": [
               {
                    "LineNumber": 1,
                    "ColumnNumber": 85,
                    "ClassName": "line 1, column 85",
                    "FileName": "https://*****",
                    "MethodName": "global code"
               }
          ]
     },
     "Environment": {
          "UtcOffset": -5,
          "Browser-Width": 207,
          "Browser-Height": 319,
          "Screen-Width": 320,
          "Screen-Height": 568,
          "Color-Depth": 32,
          "Browser": "Mozilla",
          "Browser-Name": "Netscape",
          "Browser-Version": "5.0 (iPhone; CPU iPhone OS 10_1 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/54.0.2840.91 Mobile/14B72 Safari/602.1",
          "Platform": "iPhone"
     },
     "Client": {
          "Name": "raygun-js",
          "Version": "2.4.1"
     },
     "UserCustomData": {},
     "Tags": [
          "website"
     ],
     "Request": {
          "Url": "https://*****",
          "QueryString": {},
          "Headers": {
               "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 10_1 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/54.0.2840.91 Mobile/14B72 Safari/602.1",
               "Referer": "https://*****",
               "Host": "*****"
          }
     },
     "Version": "1.5.1",
     "User": {
          "Identifier": "*****",
          "IsAnonymous": true,
          "UUID": "*****"
     },
     "OccurredOn": "2016-11-05T02:12:15.73Z"
}
```

**Comment by fundead** [comment]
Looks like these are upstream browser bugs that will hopefully be addressed by the vendors - in the meantime these can be blacklisted with `onBeforeSend`, Permanently Ignoring them in the app and/or enabling ignored3rdPartyErrors for the empty stack/message case. If this issue persists or if other similar problems arise please open a new ticket.
