### ISSUE TITLE
Ignore error based on filename

### ISSUE THREAD

**Issue by UberMouse** [MindscapeHQ/raygun4js#219]
Per a customer request, they would like to be able to ignore errors based on which file it originated from.

> We have a thirdparty that throws errors that are beyond our control. But we do not want to permanently ignore the whole group. For example, we have an error in our Website bucket "Cannot read property 'browser' of undefined" but only want to ignore errors that include the filename "https://cdn.augur.io/augur.min.js"

**Comment by xt0rted** [comment]
I've run into this myself a few times. It happens(ed) when loading font awesome via their JS version which is why I had switched back to the plain css version. I don't need this at the moment but I'll throw a 👍 on here since I can see myself needing it again at some point.

**Comment by fundead** [comment]
This can be achieved using the existing onBeforeSend function as at https://github.com/MindscapeHQ/raygun4js#onbeforesend, which is a superset of the functionality proposed and would support any logic need, by inspecting the desired fileNames in the payload and rejecting based on those (as well as any other properties, e.g environment/host name/TLD). This would be beneficial in reducing API surface bloat and providing more flexible logic than we could provide with a specific API (e.g additional support for edge cases in a new dedicated function would trend towards onBeforeSend anyway).
