### ISSUE TITLE
Virtual page timing doesn't account for location path

### ISSUE THREAD

**Issue by BenjaminHarding** [MindscapeHQ/raygun4js#222]
Primary timing data creates a URL based on the location `protocol://host+pathname` whereas the virtual primary timing data is only based on the `protocol//host+virtual page`. 

Because SPA's are served by a base file anyway wouldn't it best to send the pathname also?

**Comment by fundead** [comment]
Because this would be a breaking change with existing virtual resource wildcards in effect, and as this can be added if the users choose to surface the calling static page (and reducing noise if they don't want it), we'll leave this one unimplemented by default and up to them.
