### ISSUE TITLE
2.6.1 release doesn't seem to have the responseType fix in it

### ISSUE THREAD

**Issue by kjr-lh** [MindscapeHQ/raygun4js#225]
The tag has the fixes in, but I can't see the changes from https://github.com/MindscapeHQ/raygun4js/commit/060c9b995590bc40d8bfa7a8259d86f83872a0e1 in the 2.6.1 release itself

**Comment by UberMouse** [comment]
Not sure why 2.6.1 wouldn't have that fix in it, but the latest release (2.6.4) does so I'd suggest just using that one.
