### ISSUE TITLE
2.6.2. Uncaught ReferenceError: raygunBreadcrumbsFactory is not defined

### ISSUE THREAD

**Issue by jherax** [MindscapeHQ/raygun4js#226]
The recent update of raygun4js **v.2.6.2** is trhowing the following error:

```javascript
raygun.vanilla.js:1681 Uncaught ReferenceError: raygunBreadcrumbsFactory is not defined
```

**Comment by UberMouse** [comment]
Hey, sorry about this. I updated the order the files were concatenated together for the raygun.js task but I must have forgotten to do it for the other two. I've updated the Gruntfile and built them with the right order, released as v2.6.4.

**Comment by jherax** [comment]
Thanks @UberMouse, but the v**2.6.4**. is not in npm, the last one is **2.6.1**

**Comment by UberMouse** [comment]
Sorry about that, just published it now.

**Comment by jherax** [comment]
Thanks a lot!
