### ISSUE TITLE
use in react native throws exception on first use of module 

### ISSUE THREAD

**Issue by ofirgeller** [MindscapeHQ/raygun4js#229]
This is the error message. not very helpful but maybe someone has an idea what is wrong.

```
Attempted to assign to readonly property.
<unknown>
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:103066:13
<unknown>
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:103074:7
<unknown>
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:103057:33
<unknown>
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:103061:3
loadModuleImplementation
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:109:12
guardedLoadModule
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:70:36
_require
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:54:77
<unknown>
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:47642:25
loadModuleImplementation
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:109:12
guardedLoadModule
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:70:36
_require
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:54:77
<unknown>
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:1260:19
loadModuleImplementation
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:109:12
guardedLoadModule
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:63:45
_require
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:54:77
global code
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:105952:9

```

version: 2.6.0-SNAPSHOT.6

**Comment by fundead** [comment]
That does looks odd, unfortunately yep there's not too much info for us to work with there. What version of React Native are you using, and are you writing your app in ES2015/ES5/Typescript?

Can you paste your `rg4js()` config lines and import statements you've used to integrate with the provider? Does it work correctly with iOS (if you're using that)?

As this is a debug mode error, it might be helpful to run it up with the Chrome dev tools attached and break on error enabled, to what statement is failing. If you can get us a screenshot of this that'd be very helpful.

**Comment by ofirgeller** [comment]
@fundead  Happy to answer any questions.

react native version is 0.44.2
I am compiling Typescript into ES2015 then using babel.

I copy pasted the line from the guide, with the exception of using our real api key
```
  import rgjs from 'raygun4js';

  rgjs ('enableCrashReporting', true);
  rgjs ('apiKey', 'add_your_api_key_here');
  rgjs ('boot'); // This call must be made last to start the provider
```

However no lines need to be run to get the exception, simply importing the module is enough. 

I am not using iOS at the moment and I am unable to test if it would work on iOS.

This is the offending line:
`  (function(wind) { wind['RaygunObject'] = 'rg4js'`

After the exception wind it undefined, the I see raygun catching and setting some properties of this exception  (TypeError: Cannot set property 'RaygunObject' of undefined).

That some how effects react to the point that it throws this error
"Module AppRegistry is not a registered callable module (calling runApplication)"

There seems to be an assumption that 'this' will be the window object and that is what is being passed into the function that throws. that assumption not being correct leads to the exception.

**Comment by ofirgeller** [comment]
Changing this line umd.into.js

`var windw = this;`

to 
  
`var windw = this || global;`

Makes the error go away. You might want to do this

`var windw = this || window || global ;`

To future proof.

**Comment by fundead** [comment]
Just an update on this one, I've tested and merged your proposed fix which looks good, and will get it up on the CDN today as v2.6.5.

**Comment by ofirgeller** [comment]
@fundead  👍  thanks!
