### ISSUE TITLE
Configuration options

### ISSUE THREAD

**Issue by bjornbos** [MindscapeHQ/raygun4js#236]
The documentation about the configuration of Raygun is so confusing. Can I set all options via the 

    rg4js('options', {}) 

method? Or only the listed parameters in that section of the documentation, which would mean it excludes options like 'disableAutoBreadcrumbs'. And when should I use 'disableAutoBreadcrumbs' and when it's opposite 'enableAutoBreadcrumbs'? What if I do

    rg4js('options', {
        disableAutoBreadcrumbs: true,
        enableAutoBreadcrumbs: true
    });

Please make that section of the documentation more clear to us users.

**Comment by fundead** [comment]
You cannot - the only options that can be set in the `rg4js('options')` call are the ones present in that section in the documentation. These are initialization options that need to be set at boot time. The init options are:

```
rg4js('options', {
  allowInsecureSubmissions: true,
  ignoreAjaxAbort: true,
  ignoreAjaxError: true,
  debugMode: true,
  ignore3rdPartyErrors: false,
  wrapAsynchronousCallbacks: true,
  excludedHostnames: ['\.local'],
  excludedUserAgents: ['Mosaic'],
  disableErrorTracking: false,
  disablePulse: false,
  pulseMaxVirtualPageDuration: 1800000,
  pulseIgnoreUrlCasing: false
});
```

The breadcrumbs API functions are commands that are executed during the page lifecycle, and are of the form:

`rg4js('enableAutoBreadcrumbs');`
`rg4js('logContentsOfXhrCalls', true);`
`rg4js('recordBreadcrumb', 'breadcrumb-message', {object: 'that will be attached to the breadcrumb custom data'})`

The default is for `enableAutoBreadcrumbs`, so if you wanted to disable breadcrumbs functionality currently you can call `rg4js('disableAutoBreadcrumbs')`.

This is a v1.0 release of this feature, and we appreciate the feedback that the API is a bit hard to understand. We'll be reducing the API surface and tidying up the docs soon to resolve this issue.
