### ISSUE TITLE
Add support for capturing unhandled promise rejection errors

### ISSUE THREAD

**Issue by UberMouse** [MindscapeHQ/raygun4js#244]
Unhandled promise rejection errors don't go through `window.onerror` which results in us not capturing them. Browser support is currently spotty but it appears like they are supposed to go through `window.onunhandledrejection`. It seems like most Promise polyfills handle this correctly but only Chrome does natively.

A workaround to attempt to catch `window.onunhandledrejection` errors (assuming the handler is supported in the browser context) would be to do the following
```
window.onunhandledrejection = function(evt) {
    rg4js('send', evt.reason);
};
```

**Comment by BenjaminHarding** [comment]
Support for this feature has been added
