### ISSUE TITLE
DOMExceptions lose error message

### ISSUE THREAD

**Issue by DanielGibbsNZ** [MindscapeHQ/raygun4js#247]
When sending some exceptions, like Chrome's `DOMException`, the error message sent to raygun is "Script Error", with no trace of the original error message (e.g. `Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).`

The error object looks like this:

    {
        code: 18,
        message: "Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).",
        name: "SecurityError",
        __proto__: DOMException
    }

Occurs reliably on Chrome 60.0.3112.78 (64-bit) on Ubuntu 16.04 with Raygun4JS 2.7.1 but have also seen the same behaviour on other versions of Chrome and operating systems.

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
