### ISSUE TITLE
Importing raygun in React Native changes the stacktrace for all logs

### ISSUE THREAD

**Issue by SuhairZain** [MindscapeHQ/raygun4js#248]
Hi,
We've currently setup raygun to be used only in production mode, using the `__DEV__` flag in React Native and we have verified that the code block which setups raygun isn't called during development.

However, even if we only import raygun at the top of the file, using `import raygun from 'raygun4js'`, without calling any raygun functions, the console logs seems to lose the stacktrace, instead showing that the log came from inside raygun. Once we remove the import, things go back to normal, with the logs showing their correct stacktrace. Could you help us figure this out?

**Comment by UberMouse** [comment]
Hi Suhair,

This might have something to do with the breadcrumbs feature, which proxies the console methods through a Raygun method so we can intercept them. To verify this, can you try running `rg4js('disableAutoBreadcrumbsConsole')` in your configuration setup and seeing if the console logs retain their correct stacktrace?

Thanks,
Taylor

**Comment by SuhairZain** [comment]
Hey,
It works. So, should I be calling the aforementioned function only in debug or production as well?

**Comment by UberMouse** [comment]
I had not realized that the way we proxied the method calls was interfering with the stacktrace attached to the console messages so I'll take a look at it when I get time to see if there is a better way.  But for now yes, I'd say turn it off during development. 

You might as well run `rg4js('disableAutoBreadcrumbs')` to turn off all the automatic breadcrumb functionality since you aren't logging errors in development so the breadcrumbs provide no purpose.

**Comment by SuhairZain** [comment]
Alright. Thank you. Closing this issue. 😄

**Comment by SuhairZain** [comment]
Hey,
Your solution of using r4js('disableAutoBreadcrumbsConsole') worked for some time but it's not working anymore. The stacktrace is lost again even though we haven't changed any code there. I've resorted to using require('rajgun4js').default only on production builds as a workaround for now. It'd be really great if you could look further into this issue.

**Comment by SuhairZain** [comment]
Hey,
I've updated the version, but the issue is still there.

**Comment by UberMouse** [comment]
Can you show me a picture of what you mean by the log losing the stacktrace and appearing to come from Raygun? I think I might be misunderstanding here

**Comment by SuhairZain** [comment]
<img width="565" alt="screen shot 2017-08-15 at 8 15 28 am" src="https://user-images.githubusercontent.com/5249794/29300247-f67f75ea-8191-11e7-980a-1299744d474d.png">

**Comment by SuhairZain** [comment]
```
import rg4js from 'raygun4js'; // Messes up the stacktrace

const isProduction = !__DEV__;
// const rg4js = isProduction ? require('raygun4js') : () => {}; // Doesn't mess up the stacktrace
```

**Comment by UberMouse** [comment]
Are you still running the `rg4js('disableAutobreadcrumbsConsole')` configuration? That still needs to be turned off if you want console.log statements to have the correct location. 

We replace warn/log/error etc on console with a proxy method that calls one of our functions and the original function so we can record a breadcrumb for each message. The browser must capture the last stack frame as the location which will be our proxy method. If I turn off the auto breadcrumbs now it shows the correct location, before the proxy method wasn't being removed correctly when you turned the feature off.

**Comment by SuhairZain** [comment]
Hi,
I'm running the disableAutobreadcrumbsConsole in the debug build. It doesn't seem to work as long as raygun4js is imported.

**Comment by UberMouse** [comment]
Can you confirm that the code you are running is from the 2.7.2-SNAPSHOT version? This sounds just like the behavior I would expect from 2.7.1 and is not the behavior I'm observing on 2.7.2-SNAPSHOT so I just want to double check before I investigate any further.

**Comment by SuhairZain** [comment]
It looks like so. In my package.json, it's 2.7.2 and running yarn shows that it's already up to date. I checked the node_modules folder and raygun's package.json is at 2.7.2-SNAPSHOT.

The workaround you had suggested worked even on 2.7.1 for some time. And then, unfortunately it stopped working. :/

**Comment by UberMouse** [comment]
Very strange, I'll take a look again tomorrow.

**Comment by SuhairZain** [comment]
Hey @UberMouse 
Were you able to find a solution to this? It seems that using require() in production to load raygun doesn't seem to work as well.

**Comment by UberMouse** [comment]
No sorry, I had some other support I had to handle yesterday. And I have some priority work I need to get done this week so I won't be able to take a look again until next week.

**Comment by SuhairZain** [comment]
Hey @UberMouse,
The issue seems to be gone now. I'm not quite sure what's happened, but the stacktrace seems to be okay now. Just wanted to let you know.

**Comment by summerwollin** [comment]
@UberMouse this is still an issue for my team using Raygun4js - v2.7.1. Disabling breadcrumbs worked for one of our environments, but not for all. We're about to disable Raygun for all but our production environment as a temporary fix as having stack traces locally is more important to us. Is https://github.com/MindscapeHQ/raygun4js/pull/249 a fix for this issue? Thanks.

**Comment by UberMouse** [comment]
It should be, #249 removes the second instance of Raygun4JS I constructed around the breadcrumbs module to capture any errors once it was released. The second instance was causing the breadcrumbs to enhance the console object twice so it couldn't be properly restored to the normal state. 

I've merged and put on the CDN under http://cdn.raygun.io/raygun4js/2.7.2/raygun.js and on NPM as v2.7.2
