### ISSUE TITLE
Stacktrace for React Native isn't applied in logs

### ISSUE THREAD

**Issue by SuhairZain** [MindscapeHQ/raygun4js#253]
Hi,
I created a sourcemap for my app and uploaded it using curl. Then I caused an undefined exception from my app which I was able to see from the dashboard. But even though the sourcemap was uploaded, the stacktrace doesn't seem to apply it. I pressed the "Reprocess this error for source maps" button at the bottom and after some time, I got a popup saying "Source mapping complete". But the stacktrace isn't changed. I refreshed the page and tried again. It doesn't seem to work.

I'm getting the following message under the stacktrace:
```
These minified files could not be obtained. Please ensure your minified files are available publicly or uploaded to the source map center.

    index.android.bundle
    [native code]
```

The following is the code I use to upload the files:
```
curl \
-X POST \
-F "url=file://reactnative.local/index.android.bundle" \
-F "file=@./android/app/src/main/assets/index.android.bundle.js.map" \
https://app.raygun.io/upload/jssymbols/w70nfa\?authToken\=************
```

**Comment by UberMouse** [comment]
Hi Suhair,

Can you send this in to us via the the [contact](https://raygun.com/about/contact) link on Raygun? I'll need some extra details best not exposed in public to investigate this and it's unlikely it will be an issue with Raygun4JS itself. 

Thanks
