### ISSUE TITLE
[Feature request] Add npmignore

### ISSUE THREAD

**Issue by Havunen** [MindscapeHQ/raygun4js#267]
When you install raygun4js package, it downloads all files from this repository. Including source files, tests, project files ( vscode ), etc. By adding `.npmignore` you can remove those files so installing package is faster.

https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by akauppi** [comment]
I'm not seeing `.npmignore` in the repo, but the package contents seem meaningful to me. 

```
./node_modules/raygun4js/
├── CHANGELOG.md
├── LICENSE
├── README.md
├── dist
│   ├── raygun.js
│   ├── raygun.min.js
│   ├── raygun.min.js.map
│   ├── raygun.umd.js
│   ├── raygun.umd.min.js.map
│   ├── raygun.umd.min.js
│   ├── raygun.vanilla.js
│   ├── raygun.vanilla.min.js
│   ├── raygun.vanilla.min.js.map
│   └── snippet
│       ├── minified.fetchhandler.js
│       ├── minified.js
│       └── minified.nohandler.js
└── package.json
```

Can this be closed?

**Comment by Havunen** [comment]
I have not checked this since reporting this issue, but if you say that is the contents of new package, I trust you :)
Closing
