### ISSUE TITLE
Possible bug, Client version is {{VERSION}}

### ISSUE THREAD

**Issue by Havunen** [MindscapeHQ/raygun4js#268]
https://github.com/MindscapeHQ/raygun4js/blob/master/dist/raygun.js#L2960-L2963

Edit: I'm quite sure this is bug because that string is sent to your back end service also.
Client
```
{Name: "raygun-js", Version: "{{VERSION}}"}
```

**Comment by BenjaminHarding** [comment]
Sorry for the late reply, but thanks for the comment. That bug was due to a bad deploy (not running the correct task before hand) and wasn't picked up on before deploying. This has since been fixed in prior versions.
