### ISSUE TITLE
packages.json doesn't have TypeScript typings reference, forces use of @types/raygun4js

### ISSUE THREAD

**Issue by PandaWood** [MindscapeHQ/raygun4js#283]
This project should add the standard npm package.json syntax for informing of TypeScript typings 
eg `"types": "typescript/index.d.ts"`

If we add this, then the TypeScript compiler will find the typings automatically.
Without this, TypeScript users are forced to import the corresponding DefintelyTyped library eg `npm add @types/raygun4js"`

**Comment by BenjaminHarding** [comment]
Thanks @PandaWood for the information :)

Just letting you know we discussed the various options and have since added the "types" information into the package.json. The PR for this has since been merged and will be deployed later today.
