### ISSUE TITLE
Module "raygun4js" has no exported member 'RaygunStatic'

### ISSUE THREAD

**Issue by VictorCoding** [MindscapeHQ/raygun4js#288]
I'm not 100% sure but I believe that this commit(https://github.com/MindscapeHQ/raygun4js/commit/62f737dd2edcc1bad538ae6a67b90b0e425cfcb1) might've been the cause of this error.

![image](https://user-images.githubusercontent.com/6878222/42707650-8b63bb76-86a0-11e8-94ad-dc5ef57b322c.png)

Am I missing something? My solution for now is to use `2.8.4` instead of `2.11.0`.

**Comment by UberMouse** [comment]
Hi @VictorCoding ,

I'll be releasing a fix for this soon.

Regards,
Taylor

**Comment by emeryowa** [comment]
Any news on when this will be released?

**Comment by UberMouse** [comment]
Hi,

Sorry about that. The work was done last month but the release to NPM didn't get done. I've just pushed v2.11.1 to NPM which should resolve this issue for you.

**Comment by VictorCoding** [comment]
@UberMouse Gracias!
