### ISSUE TITLE
How to properly include contents of XHR calls in breadcrumbs?

### ISSUE THREAD

**Issue by daneilsan** [MindscapeHQ/raygun4js#290]
Hi,

I'm trying to include the contents of requests made by my app in the breadcrumbs. Sadly after reading the documentation regarding this topic I don't know what else to do.

What I have tried so far:

After initializing Raygun (with init method), I do:

`Raygun.setBreadcrumbOption("logContentsOfXhrCalls", true)
`
but nothing changes. It's worth noting that I have also tried to set the log level with the same method without success ( `Raygun.setBreadcrumbOption("setBreadcrumbLevel", "debug") `) so maybe I missunderstood something.

The Raygun object is loaded synchronously in window before at the beginning (not async). The rest is working (error reports arrive to the dashboard but without the needed request content)

Any help will be very appreciated.

Cheers

**Comment by BenjaminHarding** [comment]
Hi @daneilsan, I've just had a look and it seems when you are using the V1 API the option to turn on XHR logging for breadcrumbs is `logXhrContents` instead of `logContentsOfXhrCalls`. 

This is an oversight in the API and we will look at fixing this in the next update.

**Comment by daneilsan** [comment]
Thanks Ben,

With the proposed change, it works perfectly. 

Thank you very much!
