### ISSUE TITLE
raygun.js does not check whether `withTags` is a function before passing it to raygun.rum.js

### ISSUE THREAD

**Issue by UberMouse** [MindscapeHQ/raygun4js#296]
This should be updated to call the function and pass the result to raygun.rum.js if it is a function.

**Comment by Widdershin** [comment]
> As above for custom data, withTags can now also accept a callback function. This will be called when the provider is about to send, to construct the tags. The function you pass to withTags should return an array (ideally of strings/Numbers/Dates).

This is a bug, since the documentation states we do this. Need to check if this is still happening, and fix it if so.

**Comment by sumitramanga** [comment]
Looks like this has been fixed within https://github.com/MindscapeHQ/raygun4js/pull/498
Closing this thread now
