### ISSUE TITLE
Is `filterSensitiveData` actually working?

### ISSUE THREAD

**Issue by dannsam** [MindscapeHQ/raygun4js#300]
Hi,

I am trying to filter out an access token from breadcrumbs that is being passed in a hash part of the callback url. It is being captured in the history.pushState navigation event.
I don't really want to disable all navigation breadcrumbs, because page shown timings seem to be quite valuable.
There are traces of `filterSensitiveData` in docs, that I hope can help with filtering data being collected in breadcrumbs. However, I cannot configure it and can't find code in the repo that anything with it. Is it still a working feature ? Should the docs be updated to showcase its usage ?

**Comment by BenjaminHarding** [comment]
Hi @dannsam, by default the `filterSensitiveData` option only filters any `customData` set and so this won't include breadcrumbs or any other fields. 

There is one option to change the scope of this filter, if you go to the [change filter scope](https://github.com/MindscapeHQ/raygun4js#filtering-sensitive-data) part of the readme. 

```js
// Filter out fields from the entire payload
rg4js('setFilterScope', 'all'); 
```

Another option is to use the [`onBeforeSend` method](https://github.com/MindscapeHQ/raygun4js#onbeforesend) and you can modify the payload manually there. 

Let us know if this is still an issue and we can investigate further :)
