### ISSUE TITLE
APi key lenght = 22 and not 24 cause failing the send of report 

### ISSUE THREAD

**Issue by dario-colombo** [MindscapeHQ/raygun4js#307]
the newly generated API key has lenght=22 (while I have some old app with API key lenght=24)
this 22 length will cause this  line of code to never being evaluated true
https://github.com/MindscapeHQ/raygun4js/blob/ecdf294c382eb5902e740b61db09a2f1b321980e/src/raygun.js#L549
resulting in sendSavedErrors() to never send the stored error in the local storage.
please fix the API key generation to go back to 24 or update line 549 to match the new API length

**Comment by UberMouse** [comment]
The fix for this has just been released
