### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by dylang** [MindscapeHQ/raygun4js#31]
If this client is different than the Node client, it would be helpful to publish this one to npm as well for those that use npm for all package management (frontend and backend) instead of bower.

This makes it easy to add raygun4js to the code by using 

```
var raygun = require('raygun4js');
raygun.init(process.env.RAYGUN_API_KEY).attach();
```

in our frontend code, and use browserify to build the bundle.

**Comment by JLarky** [comment]
It looks like you can use something like that

`npm install --save git+https://github.com/MindscapeHQ/raygun4js.git`

and in browserify
``` javascript
require('raygun4js'); // adds raygun to window.Raygun 
Raygun.init(RAYGUN_API_KEY).attach();
```
