### ISSUE TITLE
Version 2.15.0 UMD - raygunNetworkTrackingFactory is not defined

### ISSUE THREAD

**Issue by TravisDuncombe** [MindscapeHQ/raygun4js#319]
The current latest version 2.15.0 the `raygunFactory` is referencing `ragyunNetworkTrackingFactory`, but it is undefined.

**Comment by BenjaminHarding** [comment]
Thanks for the feedback @TravisDuncombe. I'll have a look at this later today and get a new release sorted

**Comment by UberMouse** [comment]
I've fixed this in release v2.15.1 which has been published to NPM and pushed to the CDN. Sorry about this @TravisDuncombe!

**Comment by TravisDuncombe** [comment]
No worries, thanks for the quick fix!
