### ISSUE TITLE
Remove "tracking xhr response for" logs

### ISSUE THREAD

**Issue by emeryowa** [MindscapeHQ/raygun4js#333]
After I upgraded to raygun4js 2.16.0 it logs "tracking xhr response for" to the browser console for each network request. Is it possible to remove those logs?

**Comment by UberMouse** [comment]
Hi @emeryowa,

This should only be happening if you have debug mode turned on in Raygun4JS. If you turn off debug mode this log message will go away.

Regards,
Taylor
