### ISSUE TITLE
mapping react-native error to source from minified files

### ISSUE THREAD

**Issue by k4Shinigami** [MindscapeHQ/raygun4js#342]
I am trying to integrate raygun into our react native application and am successful at capturing errors from the application/crash. But the error stacktrace doesn't map back to source. 

I was following the guide for [react native](https://raygun.com/documentation/language-guides/javascript/crash-reporting/react-native/) and looking through the guide for [source-maps](https://raygun.com/documentation/language-guides/javascript/crash-reporting/source-maps/), which doesn't have details for react-native.

I generated the bundle and sourcemap for release using:
```
react-native bundle \
  --dev false \
  --platform android \
  --entry-file index.js \
  --bundle-output index.android.bundle \
  --sourcemap-output index.android.bundle.map
```

and uploaded to the bundle and map to the Js Source. Then trying to re-process for sourcemaps on the error gave : `These minified files could not be obtained`.
![Screen Shot 2019-10-25 at 10 41 05 AM](https://user-images.githubusercontent.com/38292450/67581021-4675a600-f715-11e9-9c27-b083dfcb8c1e.png)

Please let me know if I am missing something.

Cheers!!

**Comment by k4Shinigami** [comment]
any more info for this?

**Comment by mduncan26** [comment]
Hi @k4Shinigami 

Thank you for reporting this issue. We will require a developer to look further into this issue for you. Unfortunately we do not have capacity to do so this week. A developer will look into this next week and will contact you after they have had a chance to investigate. Thank you for your patience.

Regards,
Mitchell.

**Comment by k4Shinigami** [comment]
thank you @mduncan26 . I would appreciate any feedback on this.

**Comment by BenjaminHarding** [comment]
Thanks for reporting the issue @k4Shinigami.

At this time we do not have any additional information to resolve the issue you are currently experiencing. We do have a bit of work around our react-native support coming up on our roadmap however and once this is complete we can let you know? 

It probably will not be this year unfortunately given the time left in the year.

**Comment by k4Shinigami** [comment]
Thank you @BenjaminHarding - I will reach out to the support to understand this before moving to a different provider. This will be a crucial feature for identifying the crashes. Not sure if it would make a difference, but prioritizing this would be beneficial to using raygun with react native.

**Comment by SuhairZain** [comment]
Hi @BenjaminHarding @mduncan26 Do you have any updates on this? Is the RN support better now?

**Comment by BenjaminHarding** [comment]
Hi @SuhairZain, the exciting news is that we are working on better react-native support but it is not at a testing stage just yet. We will make sure to post an update when we have more news

**Comment by MWaqasHussain-dev** [comment]
any thing on this?

**Comment by mduncan26** [comment]
Hi @MWaqasHussain-dev 

Our new Raygun4ReactNative provider is on pause until December. We also hope to have a beta version of this provider out by the end of the year. We will update this thread when there has been a change in the scheduling. 

Thank you,
Mitchell.

**Comment by Widdershin** [comment]
Apologies about the lack of updates, but [raygun4reactnative](https://raygun.com/documentation/language-guides/react-native/crash-reporting/installation/) is now the recommended approach for crash reporting with React Native.
