### ISSUE TITLE
Raygun not working on Ionic 4 with cordova-plugin-ionic-webview on iOS

### ISSUE THREAD

**Issue by BartBakker82** [MindscapeHQ/raygun4js#347]
Hello,

I can't get Raygun to log errors on iOS when using the Ionic 4 framework with the cordova-plugin-ionic-webview plugin. It looks like this is because the default scheme of the cordova-plugin-ionic-webview plugin is set to ionic://... on iOS. The function computeStackTraceFromStackProp from tracekit.js doesn't have this scheme in the regex expressions I see there. Is it possible to add this scheme if this is indeed the problem?

**Comment by BartBakker82** [comment]
Hi,

For others that might be struggling with this issue, I found a fairly easy workaround that doesn't seem to have any nasty side effects. According to the documentation of cordova-plugin-ionic-webview, it's possible to set another scheme for iOS (https://github.com/ionic-team/cordova-plugin-ionic-webview#iosscheme). When you set the scheme to 'httpsIonic', the Tracekit regex seems to pick up the stacktrace and log the errors.

**Comment by BenjaminHarding** [comment]
Thanks for the update @BartBakker82, it's really appreciated :)
