### ISSUE TITLE
Prevent sending network errors to raygun

### ISSUE THREAD

**Issue by bsubedi26** [MindscapeHQ/raygun4js#366]
Hello,

We're facing a specific issue where we are posting network errors to raygun from our front end apps, which contributes towards the total count quota.

Is it possible to prevent some network errors from being sent to raygun (user loses internet connection, etc.). We are actively pinging our auth session endpoint every X seconds and its resulting in errors being sent to raygun.

We are using the native browser `fetch` to make the request. Example code:
```
 const { token } = await fetch(`/session`)
        .then(r => ...})
        .catch(err => {
          // can we prevent the error from being sent to raygun here?
          return err
        })
```
One option that seems to work is to return `false` in the `onBeforeSend` listener, but wouldn't that other network errors (not just /session request from being sent to raygun? - Same concern as if we ignored the raygun error in dashboard.)

```
const beforeSendHandler = (payload) => {
  const { Error = {} } = payload.Details || {}
          if (Error.Message === 'Failed to fetch' && Error.ClassName === 'TypeError') {
            return false
          }
          return payload
}
rg4js('onBeforeSend', beforeSendHandler)
```

Would this be a bug in the raygun lib because any error in this `.then()` will become an unhandled promise rejection?
https://github.com/MindscapeHQ/raygun4js/blob/master/src/raygun.network-tracking.js#L189

**Comment by BenjaminHarding** [comment]
Hi @bsubedi26,

Thanks for reporting the issue. I would need to do a little more investigation into your question about the possible bug. 

In general however, I would expect the network-tracking portion of the provider shouldn't interfere and so if your `fetch` call has a `.catch` attached then it shouldn't be picked up as an unhandled promise rejection. 

You can also disable the unhandled promise rejection automatic error handling by [disabling the option](https://github.com/MindscapeHQ/raygun4js#initialization-options): 

```js
rg4js('options', {
  captureUnhandledRejections: false
});
```

This would however mean that all unhandled promises would not be tracked. 

Like you said, returning a falsely value when using the [`onBeforeSend`](https://github.com/MindscapeHQ/raygun4js#onbeforesend) listener is another option. You could also use the stack-trace to see if the it's coming from the same file/line number which would help to limit the cases where it would be discarded. 

Hope that helps!

**Comment by bsubedi26** [comment]
@BenjaminHarding Thanks for the response. We did think about the option to set `captureUnhandledRejections: false` but it would have more a bigger outcome where it could ignore errors that we want to report to raygun.

One way I simulated this error [notice the difference between a non fetch promise reject error and fetch promise reject error]:

### Non fetch error
```
const rejectPromise = (ms) => new Promise((resolve, reject) => setTimeout(reject, ms))

await rejectPromise(2000) // When not wrapped in catch - this reports the error to raygun

// When wrapping in catch - this error does not get reported to raygun
try {
      await rejectPromise(2000)
    } catch (err) {
      console.log('.catch error: ', err)
}
```

### Fetch error
```
// It doesn't matter if fetch is wrapped in catch or not - both scenarios results in the error being reported to raygun
try {
      await window.fetch(url, options)
    } catch (err) {
      console.log('.catch error: ', err)
}
```

Is the above expected behavior? Thanks!

**Comment by BenjaminHarding** [comment]
That is the downside of disabling the `captureUnhandledRejections` option, so I can see why that is undesired. 

As to the behaviour, I would have expected it to be the same between usages. That said, I'd need to investigate it further to fully confirm this. 

Thanks again for the additional details!

**Comment by bsubedi26** [comment]
@BenjaminHarding Thanks for taking the time to look into it. Any update on this?

**Comment by BenjaminHarding** [comment]
@bsubedi26 No update on this just yet sorry. I'll see if we can look into it over the next few days and get back to you :)

**Comment by BenjaminHarding** [comment]
@bsubedi26 I've replicated issue you have described, so it does appear that `fetch` calls which are handled always results in a unhandled exception raised.  

I don't have an immediate solution for the issue to bring it to parity at this stage but thought I would give you update to let you know I'm thinking about it :)

**Comment by bsubedi26** [comment]
@BenjaminHarding Hey there, any updates on this?

**Comment by BenjaminHarding** [comment]
No updates on this just yet @bsubedi26. I'll shout out when we further look into it

**Comment by darcythomas** [comment]
@BenjaminHarding @bsubedi26 The code fix for this has been released to production now.

(You may need to reload the page (or update nuget, npm if you are using those) to pick up the changes.)
