### ISSUE TITLE
ionic iOS app error not being reported

### ISSUE THREAD

**Issue by nirajrajbhandari** [MindscapeHQ/raygun4js#367]
Hi guys,

We have an **ionic-cordova** hybrid application.

For our raygun configuration , we have **`ignore3rdPartyErrors: true`.** With this flag enabled, error is not reported whenever stacktrace is **`null`**.

Our ionic app is configured such that the base url is set to **`ionic://app`**. So the error stack would have link to files that looks something like:

`ionic://app/main.123adbas234.js:123534:15`.

**Looks like there is an issue on the code that parses the error stack depending on the browser engine.**
https://github.com/MindscapeHQ/raygun4js/blob/master/tracekit/tracekit.js#L671
**[ Specifically the regex defined to identify the error stack depending on the browser engine ]**

The base url **`ionic://app`** do not satisfy the regex defined for any of:
- gecko,
- chrome _OR_
- winjs

Stacktrace is returned as `null`. Therefore, **the error is not reported to raygun dashboard.**

**Note:** The error is reported if the link to the file follow pattern of having `http | https` protocol.

### Reproduction Steps
- setup an ionic iOS app with configuration
```
   <preference name="UseScheme" value="true" />
```
- configure the raygun application with debug mode enabled, `debugMode: true`.
- on codebase, mock an error
```
 throw new Error('Send to raygun');
```

- view the debug logs using browser devtool.

### Screenshot
![Screen Shot 2020-08-24 at 12 41 47 PM](https://user-images.githubusercontent.com/49074337/91090510-0ec3dd00-e60a-11ea-99e6-484cba972cad.png)

### Specs
- Raygun@2.20.1

**Comment by BenjaminHarding** [comment]
Thanks for the investigation @nirajrajbhandari. 

As you have alluded too, I would imagine a fix for this would be to create a new regex to identify the `ionic://app` stack-traces.

I'd be happy to review a PR to fix this address this issue but otherwise have notified the team of the issue. 

Thanks!

**Comment by nirajrajbhandari** [comment]
@BenjaminHarding thanks for the prompt response. Sure I can try to resolve the issue.

**Comment by BenjaminHarding** [comment]
@niraj-rajbhandari Thanks again for the fix. A new version has been released and so this is no longer an issue :)
