### ISSUE TITLE
No Stacktrace when using custom url scheme

### ISSUE THREAD

**Issue by sithwarrior** [MindscapeHQ/raygun4js#379]
Im experiencing an error that looks like #367 

With the latest updates to Cordova and Cordova-iOS6, we now have custom url schemes, and apps are no longer hosted on http://localhost:8080

Using the new custom url scheme default being app://localhost, results in raygun sending results with empty stack traces, and the "Script Error" moniker instead.

we could add the app:// url scheme to the regex as the fix for the ionic webview, but the scheme is configurable, so someone else may opt for a different url scheme.

`<preference name="scheme" value="app" />
<preference name="hostname" value="localhost" />` 
[https://cordova.apache.org/announcements/2020/06/01/cordova-ios-release-6.0.0.html](url)

New Cordova iOS apps must use Cordova-iOS6, as the older versions contain code, that apple will no longer accept in app store submissions.

**Comment by BenjaminHarding** [comment]
Thanks for the information @sithwarrior. 

It's certainly great to know that you can configure the scheme and hostname in Cordova applications. We will probably want to ensure that people using a custom url setup are also supported or can configure the client at least. 
 
I'll let the team know about this issue and they will be in touch.
