### ISSUE TITLE
Latest 2.22.1 throws an error in React Native application

### ISSUE THREAD

**Issue by oleksandr-dziuban** [MindscapeHQ/raygun4js#397]
In latest v2.22.1 I detected that access to browser document is requested. as result app throws an error ``Property 'document' doesn't exist``. Looks like issue was present in latest version and all ``non-browser`` envs are broken now.
With version v2.21.1 everything is OK. 
Could you please check and maybe change this piece of code to ``typeof document !=== undefined`` to avoid this issue?
Thanks

Issue is present in raygun.umd.js file on 1152th line:
![image](https://user-images.githubusercontent.com/5430640/111916527-12c2bb00-8a84-11eb-8aae-0756e843a234.png)

**Comment by krishnaKapadia** [comment]
Hi Oleksandr,

Thanks for bringing this issue to our attention and I am investigating this issue. We recommend that applications built on `react-native` migrate to using our `raygun4reactnative` SDK. We will no longer look to support React Native applications with our `raygun4js` SDK. Please take the time to look over our [documentation](https://raygun.com/documentation/language-guides/react-native/) related to our React Native support for Crash Reporting and RUM. Please let me know if you have any questions.

Thanks,
Krishna

**Comment by oleksandr-dziuban** [comment]
> Hi Oleksandr,
> 
> Thanks for bringing this issue to our attention and I am investigating this issue. We recommend that applications built on `react-native` migrate to using our `raygun4reactnative` SDK. We will no longer look to support React Native applications with our `raygun4js` SDK. Please take the time to look over our [documentation](https://raygun.com/documentation/language-guides/react-native/) related to our React Native support for Crash Reporting and RUM. Please let me know if you have any questions.
> 
> Thanks,
> Krishna

Thanks a lot! Have a great day
