### ISSUE TITLE
2.22.* `document` reference isn't compatible with React-Native

### ISSUE THREAD

**Issue by toddpi314** [MindscapeHQ/raygun4js#400]
2.21.* and before is compatible with React-native.
Beware, `^2.x.x` will pull in 2.22.*, which will throw an error on import in React-native because of the missing `global.document` reference

🙇🏼

**Comment by krishnaKapadia** [comment]
Hi Todd,

Thanks for posting about this issue, we are currently in the process of working through how we can best resolve this. We highly recommend that applications built on react-native migrate to using our raygun4reactnative SDK. We will no longer look to support React Native applications with our raygun4js SDK. 

Please take the time to look over our [documentation ](https://github.com/MindscapeHQ/raygun4reactnative) related to our React Native support for Crash Reporting and RUM.

Cheers,
Krishna
