### ISSUE TITLE
Uncaught (in promise) TypeError cannot be caught

### ISSUE THREAD

**Issue by takwing** [MindscapeHQ/raygun4js#430]
Why "Uncaught (in promise) TypeError: Failed to fetch" is still reported even I have included the .catch block already?
or I am doing something wrong?

```
try {
	fetch('http://invalid_domain.local/image.jpg')
	.then(response => {
		if (!response.ok) {
			throw new Error(response.statusText || 'error in fetching image');
		}

		return response.blob();
	})
	.then(
		blob =>
			new Promise((resolve, reject) => {
				const reader = new FileReader();
				reader.onloadend = () => resolve(reader.result);
				reader.onerror = reject;
				reader.readAsDataURL(blob);
			})
	)
	.then(imageBased64Encoded => {
		// further processing based on imageBased64Encoded
	})
	.catch(error => {
		console.log('get previewImage Error:', error);
	})
} catch (err) {
	console.error('exception caught for previewImage:', err);
}
```

![VirtualBoxVM_WgTiDMjFPR](https://user-images.githubusercontent.com/342481/140029923-44f2c84d-d716-42cf-b96b-4da129aaf044.jpg)

**Comment by takwing** [comment]
probably this is already a WIP item https://github.com/MindscapeHQ/raygun4js/pull/375

**Comment by Olwiba** [comment]
Hi @takwing, thanks for reporting this & bringing it to my attention!
This looks like a bug & appreciate you linking through the work in progress PR.

I'll get someone to take a look into the PR & get a fix out, just need to slot this in around other roadmap items.

**Comment by smathson** [comment]
Wow @takwing thank you so much for reporting this, I've been banging my head against a wall off and on for awhile now on this issue thinking I was going crazy and didn't understand Promise fundamentals at all and never actually considered it was the Raygun library at fault. At least I know I'm not going crazy!

**Comment by takwing** [comment]
@smathson   you are welcome.  I experienced the same when I noticed the uncaught error.  I had been trying all sort of ways to handle that too.

**Comment by darcythomas** [comment]
The code fix for this has been released to production now.

(You may need to reload the page (or update nuget, npm if you are using those) to pick up the changes.)
