### ISSUE TITLE
Can't download or product version on ReadMe file. 404 error.

### ISSUE THREAD

**Issue by Daniyaldehleh** [MindscapeHQ/raygun4js#431]
links to the minified builds at https://github.com/MindscapeHQ/raygun4js#manual-download are returning a 404 for both the production and development versions.
Production URL
https://raw.githubusercontent.com/MindscapeHQ/raygun4js/master/dist/raygun.min.js
Development URL
https://raw.githubusercontent.com/MindscapeHQ/raygun4js/master/dist/raygun.jsI noticed that the current build is returning an error
https://travis-ci.org/github/MindscapeHQ/raygun4js
is this why these files might be missing?

**Comment by Daniyaldehleh** [comment]
& when I control save it, it doesn't get saved. Immediately gets disappeared.

**Comment by krishnaKapadia** [comment]
Hi Daniyaldehleh,

Thanks for point that out, I have gone ahead and updated the links to point to our cdn. They should now be working as intended for you.

Cheers,
Krishna
