### ISSUE TITLE
React native compatibility for raygun4js v2.22.*+

### ISSUE THREAD

**Issue by uyend** [MindscapeHQ/raygun4js#437]
Hey there, 

Is there a plan on making this compatible with React native (on the roadmap somewhere? If it is what's the guestimate on getting that out?) or are we forced to use raygun4reactnative?

**Comment by krishnaKapadia** [comment]
Hi Uyend,

We highly recommend that applications built on react-native migrate to using our raygun4reactnative SDK. We no longer look to support React Native applications with our raygun4js SDK.

[Here ](https://github.com/MindscapeHQ/raygun4reactnative)is some documentation related to our React Native support for Crash Reporting and RUM.

Cheers,
Krishna
