### ISSUE TITLE
Lazy-load?

### ISSUE THREAD

**Issue by pavelloz** [MindscapeHQ/raygun4js#438]
Hey,

My company is thinking about switching to raygun to keep our ruby and JS errors in the same app.
I could not find how to lazyload raygun JS when error occurs like sentry does ( https://docs.sentry.io/platforms/javascript/install/lazy-load-sentry/ ).

This is a pretty big deal for very fast websites, is it possible to do it? If not, are you planning on releasing such version?

**Comment by darcythomas** [comment]
Hey @pavelloz I believe this is an out of the box feature of Raygun.

If you have a look in the (js getting started guide)[https://raygun.com/documentation/language-guides/javascript/crash-reporting/installation/] you will see a minimized snippet of javascript.

```javascript
!function(a,b,c,d,e,f,g,h){a.RaygunObject=e,a[e]=a[e]||function(){
  (a[e].o=a[e].o||[]).push(arguments)},f=b.createElement(c),g=b.getElementsByTagName(c)[0],
  f.async=1,f.src=d,g.parentNode.insertBefore(f,g),h=a.onerror,a.onerror=function(b,c,d,f,g){
  h&&h(b,c,d,f,g),g||(g=new Error(b)),a[e].q=a[e].q||[],a[e].q.push({
  e:g})}}(window,document,"script","//cdn.raygun.io/raygun4js/raygun.min.js","rg4js");
```

It is not immediately obvious, it is minified after all! What it does is creates a bootstrap error logger. So any errors which occur before the main Raygun js file load are still caught.
Then it loads the main Raygun js file, and begins sending the crash reports (real user monitoring, etc) to the Raygun servers.


Does that answer your question?
Or are you think of something else?

**Comment by pavelloz** [comment]
Ouh, so the main script (`cdn.raygun.io/raygun4js/raygun.min.js`) in this case isnt loaded until an error occurs?
Thats a very concise and elegant way of doing it, to the point i didnt even expect that this snippet would do it :))

Thank you and props for a very elegant solution :)
