### ISSUE TITLE
`rg4js('boot')` not just for React Native

### ISSUE THREAD

**Issue by mcfarljw** [MindscapeHQ/raygun4js#458]
```
rg4js('boot'); // For React Native only: add this after all other config options have been called
```

It's a bit confused from the docs which imply that `rg4js('boot')` is only required with React Native apps. I have an Ionic Capacitor app and errors don't send unless I call the boot action.

As a bonus it's also be great to get the typing updates as they don't currently include the boot parameter which requires doing `rg4js('boot' as any)` for TypeScript to compile. Here is the link to the current typings: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/raygun4js

**Comment by Widdershin** [comment]
Hi @mcfarljw,

Thanks for the issue. Sorry about any confusion around this behaviour.

The current plan is to fix the underlying issue that requires calling `'boot'` manually, which I've opened #454 to track. That should hopefully be a smoother experience for users.

**Comment by mcfarljw** [comment]
Thanks I've subscribed to that issue instead.

**Comment by Codex-** [comment]
To address the `'boot' as any` issue I have raised a PR here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61397

This simply adds the API: `(key: "boot"): void;`

**Comment by Codex-** [comment]
The typings PR has been merged and released :)
