### ISSUE TITLE
Uncaught TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by it-ony** [MindscapeHQ/raygun4js#48]
We use the minified version of raygun since 8 days I see an error caused by raygun.

```
Uncaught TypeError: Converting circular structure to JSON
     at ? line 7, column undefined (http://www.spreadshirt.de/Public/Tablomat/build/8.20.5/sprd/lib/raygun.js:7)
```

Within the source in line 7 I cannot see a JSON.stringify, but maybe this due a call.

**Comment by vpllan** [comment]
Getting the same error. Using //cdn.raygun.io/raygun4js/raygun.min.js (Raygun4js - v2.3.3 - 2016-06-21). Disabling the tool...
