### ISSUE TITLE
Breadcrumb message will always be "Failed request to undefined" due to typo

### ISSUE THREAD

**Issue by RShergold** [MindscapeHQ/raygun4js#508]
https://github.com/MindscapeHQ/raygun4js/blob/fe73f53dd0af9dd8002025eb6fdd13238eb01de9/src/raygun.breadcrumbs.js#L478

`error.requestUrl` should be `error.requestURL`

**Comment by Hamish-taylor** [comment]
Hello @RShergold,
Thank you for brining this issue to our attention.
I have created a [PR](https://github.com/MindscapeHQ/raygun4js/pull/516) to fix the issue

**Comment by Hamish-taylor** [comment]
Hello @RShergold,
A fix for this issue was deployed in version 3.0.1 of raygun4js.
