### ISSUE TITLE
Changelog for v3.0.0

### ISSUE THREAD

**Issue by DercilioFontes** [MindscapeHQ/raygun4js#515]
A new major version, v3.0.0, has been available on npm since 15 Jan 2024.
There is no CHANGLOG about that release version.
Could it have any breaking changes?

![Screenshot 2024-01-21 at 6 50 09 PM](https://github.com/MindscapeHQ/raygun4js/assets/20172847/16299a0a-4db3-4ed0-86c7-fd4fe00cafb7)

**Comment by Hamish-taylor** [comment]
Hello @DercilioFontes,
You can find the changelog in the repo here: https://github.com/MindscapeHQ/raygun4js/blob/master/CHANGELOG.md

**Comment by Olwiba** [comment]
Yes - version 3.0.0 is ready for production usage, I will add the release to the repo now 😃

**Comment by Olwiba** [comment]
Hi @DercilioFontes - You can find the latest release added here:
https://github.com/MindscapeHQ/raygun4js/releases/tag/v3.0.0
