### ISSUE TITLE
Angular16: Could not find a declaration file for module 'raygun4js'. 

### ISSUE THREAD

**Issue by alexandrearc** [MindscapeHQ/raygun4js#517]
Hey guys,

I am trying to setup Raygun on my Angular 16 application. Following the steps the first issue I encounter is:

![image](https://github.com/MindscapeHQ/raygun4js/assets/966178/82d4b20b-7bf6-4722-88fe-c5c64ab2f563)

I followed the recommendation and run: ` npm i --save-dev @types/raygun4js`. 

After finishing the other steps from the Angular [setup](https://raygun.com/documentation/language-guides/javascript/crash-reporting/angular/) page my app doesn't load. It keeps frozen on the SSO Login page, no issues in the console or anywhere else I can see.

I also tried the CND setup and got the same behavior.

So I am not sure I what I am doing it wrong. Any ideas ?

**Comment by Deacon-McIntyre** [comment]
Hi @alexandrearc, thanks for raising this.

Yes, installing the types is something missing from our Angular documentation so I will get that updated.

As for that freezing issue, I unfortunately haven't been able to reproduce it. It doesn't sound like you are doing anything wrong, are you able to share any more details about your application to help us investigate/reproduce this? Feel free to [raise a support ticket](https://raygun.com/about/contact) if you want to send us any code that you'd rather not be public.

Other things to try would be
* can you access any other pages of your application, to narrow down if this is specific to a certain part of the app?
* if your app works on/before the SSO login page, can you try manually sending an error to Raygun from the part of the app that does work. The code to do this would be like so:
```
    try {
      throw new Error("Test error");
    } 
    catch (e) {
      rg4js('send', e);
    }
```
* Are you able to debug the app to see if there is an error occurring when the app freezes that's somehow being swallowed?

**Comment by sumitramanga** [comment]
Hi @alexandrearc 

Did you still need help with this issue or has my colleague's answer helped you out? Let us know how you get on!

Cheers,
Sumitra

**Comment by alexandrearc** [comment]
Hey @sumitramanga, 

Unfortunately I haven't had a chance to give it another try. Please feel free to close it and I can reopen again if needed.

Thanks for the support,
Alex

**Comment by sumitramanga** [comment]
Hi @alexandrearc,

No worries, will close out but please do contact us either through here or via our contact form on raygun.com if you'd like any additional assistance.

Cheers,
Sumitra
