### ISSUE TITLE
Reporting a broken URL in the docs

### ISSUE THREAD

**Issue by shiv19** [MindscapeHQ/raygun4js#528]
https://raygun.com/documentation/language-guides/javascript/crash-reporting/source-maps/#3-using-build-plugins

In this section of the docs the "webpack" link is broken.
It would also be useful to have a link to the npm package in the docs
https://www.npmjs.com/package/@raygun.io/webpack-plugin

**Comment by ProRedCat** [comment]
Thanks for catching that! Should be fixed now, and we've added the link to the npm package as well
