### ISSUE TITLE
Ping issue - Raygun4js v3.1.0 

### ISSUE THREAD

**Issue by tahmernightingale** [MindscapeHQ/raygun4js#529]
Raygun4js - v3.1.0 - 2024-05-30
 
  var url = Raygun.Options._raygunApiUrl + "/ping?apiKey=" + encodeURIComponent(Raygun.Options._raygunApiKey);

Causing multiple 404's requests to

undefined/ping?apiKey=undefined

![image](https://github.com/MindscapeHQ/raygun4js/assets/108322036/ec8ebbd6-6de3-4585-a845-0e5117574f65)

**Comment by CmdrKeen** [comment]
For visibility: This has been escalated to the team to investigate.

**Comment by CmdrKeen** [comment]
We've revered version 3.1.0 from our CDN to the prior version of 3.0.1. 

You can verify the version loaded [here](http://cdn.raygun.io/raygun4js/raygun.min.js).

3.1.0 was not yet pushed to any other package repositories or release sites.

Apologies for the issue. Thank you for reporting it too. 

I won't close this ticket. Once the team have completed the investigation and code changes, they'll update with more detail (likely in the next 24 hours).

**Comment by tahmernightingale** [comment]
Cheers mate, thanks for prompt replies

**Comment by Hamish-taylor** [comment]
Hello,
We have been able to reproduce the issue, but to ensure that we have caught the exact scenario you encountered could you please share some additional details of your setup. It would be great if you could give us a screenshot of how you are setting up Raygun4js as well as other information such as if you are using a JavaScript framework. If you prefer you can send this info to our support team. Thanks!

**Comment by tahmernightingale** [comment]
Hey Mate, 

We are using the recommended async method for setup. No major JS Frameworks.

We have the script loading on every page, however we do not setup the apiKey on every page. I believe it is those pages that we haven't configured that were making the 404 requests.

// on some pages.
<script type="text/javascript">
    rg4js('apiKey', 'paste_your_api_key_here');
    rg4js('enablePulse', true);
</script>

**Comment by Hamish-taylor** [comment]
Thanks that helped a lot. The issue lies with how Raygun4js sets its self up internally. If no setup calls are made (such as setting the apiKey or enabling a product) then the default URL is not set which then caused the issues you encountered. We have implemented checks that will prevent the pings from being sent in these cases. Given that we are heading into the weekend we will wait until next week to deploy the new patched version. 

Thank you for your help in identifying this issue

**Comment by tahmernightingale** [comment]
Sweet, glad to help

**Comment by Hamish-taylor** [comment]
Hey @tahmernightingale,

Just letting you know that we have published the patched version of 3.1.0 to the CDN. If you are curious you can find the fix in this [PR](https://github.com/MindscapeHQ/raygun4js/pull/525). 
We have also credited your account by the number of errors we caused.

Thank you again for your help!

**Comment by tahmernightingale** [comment]
Cheers Hamish, looks good thanks
