### ISSUE TITLE
traceKitWrapper bug

### ISSUE THREAD

**Issue by bjornbos** [MindscapeHQ/raygun4js#90]
I'm seeing errors in the log in this function:

    TraceKit.wrap = function traceKitWrapper(func) {
        function wrapped() {
            try {
                return func.apply(this, arguments);
            } catch (e) {
                TraceKit.report(e);
                throw e;
            }
        }
        return wrapped;
    };

Error message on the 'return func.apply' line:

JavaScript-object wordt verwacht
(translation: Javascript object expected)

**Comment by fundead** [comment]
This issue should have been fixed in a previous release, please open a new issue if you are still seeing occurrences.

Regards,

Callum Gavin
Mindscape Limited

**Comment by cjbush** [comment]
@fundead I know this is an old bug, but I'm seeing the same error in v2.20.3 of raygun.js. The stack trace looks like this:

![image](https://user-images.githubusercontent.com/5855938/97025392-031b6680-1526-11eb-8812-e5922a15697c.png)

Any insight into what might be causing this?
